version: '3'
services:
    server:
        build:
            context: .
        ports:
            - "8000:8000"
        links:
            - db
    db:
        image: mongo
        ports:
          - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: gobygame
